[tool.pytest.ini_options]
pythonpath = [".", 'src']
DJANGO_SETTINGS_MODULE = 'django_project.settings'
python_files = ["tests.py", 'test_*.py', '*_tests.py', '*_test.py']

[tool.pyright]
venvPath = "."
venv = "venv"

[tool.ruff]
line-length = 80

[tool.ruff.format]
quote-style = "single"
